# Generated by Django 4.2.1 on 2023-07-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employe', '0003_remove_employees_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_hired',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others')], default='Others', max_length=10),
        ),
    ]
