# Generated by Django 4.2.1 on 2023-07-02 14:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=50),
        ),
    ]
